---

- name: Install requirements (Debian)
  apt: name={{item}}
  with_items: [openvpn, udev, openssl]

- name: Install dependencies (Debian)
  apt: name={{item}}
  when: openvpn_use_pam_users|default(false)
  with_items: [libpam-pwdfile, python-passlib]

- name: Install LDAP dependencies (Debian)
  apt: name=openvpn-auth-ldap
  when: openvpn_use_ldap|default(false)

- name: Install password auth dependencies
  apt: name=openvpn-auth-password
  with_items: [mysql-server]
  when: openvpn_use_password
